#redisConfig:
#  host: 192.168.2.57
#  port: 8888
#redisSentinetlConfig:
#  name: books-prod-redis-master
#  endpoints:
#    -
#      host: 192.168.2.56
#      port: 20000
#    -
#      host: 192.168.2.57
#      port: 20000
#    -
#      host: 192.168.2.58
#      port: 20000