#redisConfig:
#  host: 192.168.10.98
#  port: 6666
#redisSentinelConfig:
#  name: books-dev-redis-master
#  endpoints:
#    -
#      host: 192.168.10.98
#      port: 20001
#    -
#      host: 192.168.10.90
#      port: 20000